name: build_adios_ko

on:
  workflow_dispatch:

jobs:
  build-adios:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git build-essential bc bison flex libssl-dev \
            libelf-dev ccache python3 curl wget lld clang llvm gcc-aarch64-linux-gnu

      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          path: local_repo

      - name: Checkout adios module
        uses: actions/checkout@v4
        with:
          repository: firelzrd/adios
          path: adios

      - name: Clone kernel source (GKI base)
        run: |
          mkdir kernel_workspace && cd kernel_workspace
          repo init -u https://github.com/HanKuCha/kernel_manifest.git -b refs/heads/oneplus/sm8750 -m JiuGeFaCai_oneplus_13_v.xml --depth=1
          repo --trace sync -c -j$(nproc --all) --no-tags
          rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
          rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"

      - name: Set environment variables
        run: |
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "KERNEL_DIR=$GITHUB_WORKSPACE/kernel/common" >> $GITHUB_ENV
          echo "OUT_DIR=$GITHUB_WORKSPACE/kernel/common/out" >> $GITHUB_ENV
          echo "CLANG_PATH=/usr/lib/llvm-17/bin" >> $GITHUB_ENV
          echo "PATH=$CLANG_PATH:$PATH" >> $GITHUB_ENV

      - name: Prepare kernel config
        run: |
          cd $KERNEL_DIR
          make O=$OUT_DIR LLVM=1 ARCH=arm64 CC=clang gki_defconfig

      - name: Build adios.ko
        run: |
          cd $GITHUB_WORKSPACE/adios
          make -C $KERNEL_DIR O=$OUT_DIR LLVM=1 ARCH=arm64 CC=clang M=$(pwd) modules

      - name: Upload adios.ko
        uses: actions/upload-artifact@v4
        with:
          name: adios-ko
          path: |
            adios/adios.ko
