name: build_adios_ko

on:
  workflow_dispatch:

jobs:
  build-adios:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git build-essential bc bison flex libssl-dev \
            libelf-dev ccache python3 curl wget lld clang llvm

      - name: Checkout adios module
        uses: actions/checkout@v4
        with:
          repository: firelzrd/adios
          path: adios

      - name: Clone kernel source (GKI base)
        run: |
          mkdir kernel && cd kernel
          git clone --depth=1 https://github.com/HanKuCha/kernel_platform.git -b oneplus_13 common

      - name: Set environment variables
        run: |
          echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "KERNEL_DIR=$GITHUB_WORKSPACE/kernel/common" >> $GITHUB_ENV
          echo "OUT_DIR=$GITHUB_WORKSPACE/kernel/common/out" >> $GITHUB_ENV

      - name: Prepare kernel config
        run: |
          cd $KERNEL_DIR
          make O=$OUT_DIR ARCH=arm64 gki_defconfig

      - name: Build adios.ko
        run: |
          cd $GITHUB_WORKSPACE/adios
          make -C $KERNEL_DIR O=$OUT_DIR ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- modules

      - name: Upload adios.ko
        uses: actions/upload-artifact@v4
        with:
          name: adios-ko
          path: |
            adios/adios.ko
